name: cawsc test (w eks matrix)
on:
  workflow_dispatch:

permissions:
  id-token: write   
  contents: read  

jobs:
  matrix_hello_world:
    strategy:
        matrix:
            runner: [eks-small-apg, eks-medium-apg, eks-large-apg]
    runs-on: ${{ matrix.runner }}
    steps:
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install awscli

        - name: check creds
          run: aws sts get-caller-identity

        - name: role chain
          id: my-super-cool-id-step-yeah1337            
          uses: aws-actions/configure-aws-credentials@main
          with:
            aws-region: us-east-2
            role-to-assume: arn:aws:iam::884348119369:role/role-for-eks-to-chain-into
            role-skip-session-tagging: false
            role-chaining: true

        - name: check creds again
          run: aws sts get-caller-identity