name: test gha runner
on:
  workflow_dispatch:

permissions:
  id-token: write   
  contents: read  

jobs:
  matrix_hello_world:
    strategy:
        matrix:
            runner: [eks-small-apg, eks-medium-apg, eks-large-apg]
    runs-on: ${{ matrix.runner }}
    steps:
        - name: take a nap
          run: sleep 60
        - name: say hi!
          run: echo 'Hello World, I'm running on the ${{ matrix.runner }} runner!    